name: 'cfn-nag-action'
description: 'executes cfn_nag_scan'
inputs:
  version:
    description: 'option to specify version for install'
    required: false
    default: ''
  path:
    description: 'the path/file to be scanned'
    required: false
    default: '.'
  args:
    description: 'extra arguments'
    required: false
    default: '--print-suppression'
outputs:
  results:
    description: "scan results"
    value: "${{ steps.scan.outputs.results }}"
runs:
  using: "composite"
  steps:
    - name: install cfn_nag_scan
      id: install
      run: |
        echo "::group::Installing cfn-nag"
        gem install cfn-nag --version "${{ inputs.version }}"
        echo "::endgroup::"
      shell: bash
    - name: scan
      id: scan
      run: |
        echo Scanning... && echo ""
        results=$(cfn_nag_scan ${{ inputs.args }} --input-path "${{ inputs.path }}")
        echo $results
        results="${results//'%'/'%25'}"
        results="${results//$'\n'/'%0A'}"
        results="${results//$'\r'/'%0D'}"
        echo "::set-output name=results::$(echo "$results")"

      shell: bash
